algo001=input('Digite algo: ')
print('O tipo primitivo desse valor é: ',type(algo001))
print('Só tem espaços ?',algo001.isspace())
print('É um número ?',algo001.isnumeric())
print('É alfabético ?',algo001.isalpha())
print('É alfanumérico ?',algo001.isalnum())
print('Está em maiúsculo ?',algo001.isupper())
print('Está em minúsculo ? ',algo001.islower())
print('Está capitalizada ? ',algo001.istitle())